In [2]:
pip install numpy


In [3]:
import numpy as np


In [4]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [12]:
a=np.array(42)
b=np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
random_arr=np.random.random((2,2))
print(random_arr)

[[0.37839388 0.74805807]
 [0.93450946 0.86678919]]


In [7]:
range=np.arange(0,10,2)
print(range)

[0 2 4 6 8]


In [8]:
identity=np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
arr=np.array([[1,2,3],[4,5,6]])
print("shape:",arr.shape)
print("size:",arr.size)
print("data type:",arr.dtype)
print("number of dimensions:",arr.ndim)

shape: (2, 3)
size: 6
data type: int64
number of dimensions: 2


In [14]:
zeros=np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
ones=np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)
print(temp_data.ndim)
print("shape:",temp_data.shape)
print("size:",temp_data.size)
print("data type:",temp_data.dtype)
print("number of dimensions:",temp_data.ndim)


[[22 25 20]
 [24 26 23]]
2
shape: (2, 3)
size: 6
data type: int64
number of dimensions: 2


In [18]:
print("shape:",temp_data.shape)
print("size:",temp_data.size)
print("data type:",temp_data.dtype)
print("number of dimensions:",temp_data.ndim)

shape: (2, 3)
size: 6
data type: int64
number of dimensions: 2


In [37]:
new_data=np.array([[21,23,22]])
temp_data=np.vstack([temp_data,new_data])
print(temp_data)
print(temp_data.ndim)

[[22 25 20]
 [24 26 23]
 [21 23 22]
 [21 23 22]
 [21 23 22]
 [21 23 22]
 [21 23 22]]
2


In [24]:
updated_temp_data=temp_data.copy()
print

[[22 25 20]
 [24 26 23]
 [21 23 22]
 [21 23 22]]


In [33]:
arr=np.array([[20,30,40],[50,60,70]])
print(arr[0,1])
print(arr[1,-1])

30
70


In [38]:
print(arr[:,-1:])

[[40]
 [70]]


In [39]:
sensor_error_flags=np.zeros((2,3))
print(sensor_error_flags)

[[0. 0. 0.]
 [0. 0. 0.]]


In [40]:
greenhouse_identity=np.ones((3,3))
print(greenhouse_identity)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [41]:
print(updated_temp_data, sensor_error_flags,greenhouse_identity)

[[22 25 20]
 [24 26 23]
 [21 23 22]
 [21 23 22]] [[0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [44]:
shipments=np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print(shipments)

[[50 60 55 70 65 80 90]
 [40 45 50 60 55 70 75]]


In [50]:
print(shipments[0,2])
print(shipments[1,6])
shipments[0,5]=100
print(shipments)

55
75
[[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [47]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [48]:
print(a*b)

[ 4 10 18]


In [49]:
print(a*2)

[2 4 6]


In [53]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
result=np.dot(mat1,mat2)
print(result)


[[19 22]
 [43 50]]


Broadcasting

In [54]:
a=np.array([1,2,3])
b=2
print(a+b)


[3 4 5]


In [59]:
arr=np.array([1,2,3])

print(np.exp(arr))
print(np.sqrt(arr))
print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))
print(np.expm1(arr))

[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[0.        1.        1.5849625]
[ 1.71828183  6.3890561  19.08553692]


In [61]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(np.add(x,y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))
print(np.power(x, y))
print(np.mod(x, y))


print(np.logical_and(x, y))
print(np.logical_or(x, y))
print(np.logical_not(x))
print(np.logical_xor(x, y))
print(np.greater(x, y))
print(np.less(x, y))
print(np.equal(x, y))
print(np.not_equal(x, y))
print(np.greater_equal(x, y))
print(np.less_equal(x, y))
print(np.bitwise_and(x, y))
print(np.bitwise_or(x, y))
print(np.bitwise_xor(x, y))
print(np.invert(x))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[1 2 3]
[ True  True  True]
[ True  True  True]
[False False False]
[False False False]
[False False False]
[ True  True  True]
[False False False]
[ True  True  True]
[False False False]
[ True  True  True]
[0 0 2]
[5 7 7]
[5 7 5]
[-2 -3 -4]


In [62]:
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)

/tmp/ipython-input-1519505120.py:4: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(x)
/tmp/ipython-input-1519505120.py:5: RuntimeWarning: invalid value encountered in arccos
  np.arccos(x)


np.int64(6)

In [64]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
print(farmA)

[[10 12 11]
 [ 9 11 10]
 [12 13 14]
 [ 8  7  9]]


In [69]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
print(farmA)
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
print(farmB)
print(farmC)

[[10 12 11]
 [ 9 11 10]
 [12 13 14]
 [ 8  7  9]]
[[20 19 21]
 [18 20 19]
 [22 23 21]
 [17 18 16]]
[[15 16 14]
 [14 13 15]
 [16 17 18]
 [12 11 13]]


In [73]:
print(farmA.shape)
production_all=np.array([farmA,farmB,farmC])
print(production_all.shape)
print(production_all.dtype)
print(production_all.size)
print(production_all.ndim)



(4, 3)
(3, 4, 3)
int64
36
3


In [75]:
total_per_farm =np.sum(production_all,axis=(1,2))
print(total_per_farm)

[126 234 174]


In [78]:
mean_per_farm=np.mean(production_all,axis=(1,2))
print(mean_per_farm)
var_per_farm=np.var(production_all,axis=(1,2))
print(var_per_farm)
std_per_farm=np.std(production_all,axis=(1,2))
print(std_per_farm)

[10.5 19.5 14.5]
[3.91666667 3.91666667 3.91666667]
[1.97905701 1.97905701 1.97905701]


In [80]:
hour_weights=np.array([0.5,1.0,0.75])
print(hour_weights)

[0.5  1.   0.75]


In [81]:
weighted_per_panel=np.dot(production_all,hour_weights)
print(weighted_per_panel)

[[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]


In [82]:
c=0.5
print(farmB+c)


[[20.5 19.5 21.5]
 [18.5 20.5 19.5]
 [22.5 23.5 21.5]
 [17.5 18.5 16.5]]


In [83]:
print(farmA,farmB+c,farmC)

[[10 12 11]
 [ 9 11 10]
 [12 13 14]
 [ 8  7  9]] [[20.5 19.5 21.5]
 [18.5 20.5 19.5]
 [22.5 23.5 21.5]
 [17.5 18.5 16.5]] [[15 16 14]
 [14 13 15]
 [16 17 18]
 [12 11 13]]


In [84]:
normalize=(production_all-mean_per_farm)/std_per_farm
print(normalize)

[[[-0.25264558 -3.78968364 -1.76851903]
  [-0.75793673 -4.2949748  -2.27381019]
  [ 0.75793673 -3.28439249 -0.25264558]
  [-1.26322788 -6.31613941 -2.77910134]]

 [[ 4.80026595 -0.25264558  3.28439249]
  [ 3.78968364  0.25264558  2.27381019]
  [ 5.81084826  1.76851903  3.28439249]
  [ 3.28439249 -0.75793673  0.75793673]]

 [[ 2.27381019 -1.76851903 -0.25264558]
  [ 1.76851903 -3.28439249  0.25264558]
  [ 2.77910134 -1.26322788  1.76851903]
  [ 0.75793673 -4.2949748  -0.75793673]]]


In [85]:
print(np.exp(normalize))

[[[7.76743129e-01 2.26027512e-02 1.70585433e-01]
  [4.68632346e-01 1.36369154e-02 1.02919290e-01]
  [2.13386893e+00 3.74633375e-02 7.76743129e-01]
  [2.82739901e-01 1.80690578e-03 6.20942840e-02]]

 [[1.21542738e+02 7.76743129e-01 2.66927633e+01]
  [4.42424017e+01 1.28742690e+00 9.71635149e+00]
  [3.33902240e+02 5.86216526e+00 2.66927633e+01]
  [2.66927633e+01 4.68632346e-01 2.13386893e+00]]

 [[9.71635149e+00 1.70585433e-01 7.76743129e-01]
  [5.86216526e+00 3.74633375e-02 1.28742690e+00]
  [1.61045419e+01 2.82739901e-01 5.86216526e+00]
  [2.13386893e+00 1.36369154e-02 4.68632346e-01]]]


In [114]:
print(np.max((farmA)))
panel_totals_per_farm =np.sum(production_all,axis=2)
print(panel_totals_per_farm)


14
[[33 30 39 24]
 [60 57 66 51]
 [45 42 51 36]]


reshaping

In [90]:
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(6,1)
print(reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


stacking and splitting

In [97]:
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]]
[1 2 3 4]


In [96]:
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,5))

[array([1, 2]), array([3]), array([4]), array([5]), array([6])]


In [99]:
arr=np.array([1,2,3,4,5])
print(arr[arr>3])


[4 5]


In [103]:
arr=np.array([10,20,30,40])
ind=[1,2]
print(arr[ind])

[20 30]


copy vs view

In [108]:
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
view[1]=23
print(arr)

[10 23  3]


In [112]:
copy=arr.copy()
copy[0]=123
copy[1]=23
print(arr)

[10 23  3]


saving and loading

In [113]:
arr=np.array([1,2,3])
np.save('array.npy',arr)
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3]


In [123]:
a=np.arange(10,51)
print(a)
random_arr=np.random.rand(3,3)
print(random_arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.77193281 0.26617222 0.38195058]
 [0.63524975 0.16049272 0.74554136]
 [0.12944955 0.87162396 0.96601757]]


In [125]:
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)

(3,)
int64
3
1


In [126]:
print(arr)

[1 2 3]


In [127]:
a=5
print(arr+a)

[6 7 8]


In [128]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(arr1*arr2)

[ 4 10 18]


In [131]:
a=np.arange(1,26)
print(a)
reshaped=a.reshape(5,5)
print(reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [142]:
print(reshaped[0:1])
print(reshaped[:,-1])
print(reshaped[0:3,0:2])


[[1 2 3 4 5]]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]


In [143]:
a=np.random.randint(10,100,10)
print(a)

[55 54 32 95 82 20 36 89 87 15]


In [148]:
max=a.max()
print(max)
min=np.min(a)
print(min)
mean=np.mean(a)
std=np.std(a)
print(mean)
print(std)

95
15
56.5
28.64000698323937


In [149]:
a=np.arange(1,13)
print(a.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [150]:
ones=np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [151]:
arr=np.array([1,2,3])
print(ones+arr)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [158]:
a=np.random.randint(1,51)

print(a)
divisible=(a%5 ==0)
print(divisible)


17
False


In [159]:
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
print(np.dot(mat1,mat2))

[[19 22]
 [43 50]]


In [161]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(np.diagonal(a))

[ 1  6 11 16]
